// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: api_keys.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
    organization_id,
    created_by_user_id,
    name,
    key_prefix,
    key_hash,
    scopes
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, organization_id, created_by_user_id, name, key_prefix, key_hash, scopes, last_used_at, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	OrganizationID  pgtype.UUID `json:"organization_id"`
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
	Name            string      `json:"name"`
	KeyPrefix       string      `json:"key_prefix"`
	KeyHash         string      `json:"key_hash"`
	Scopes          []string    `json:"scopes"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.OrganizationID,
		arg.CreatedByUserID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.Scopes,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedByUserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, organization_id, created_by_user_id, name, key_prefix, key_hash, scopes, last_used_at, revoked_at, created_at
FROM api_keys
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedByUserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT id, organization_id, created_by_user_id, name, key_prefix, key_hash, scopes, last_used_at, revoked_at, created_at
FROM api_keys
WHERE key_prefix = $1
LIMIT 1
`

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, keyPrefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedByUserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysByOrganization = `-- name: ListAPIKeysByOrganization :many
SELECT id, organization_id, created_by_user_id, name, key_prefix, key_hash, scopes, last_used_at, revoked_at, created_at
FROM api_keys
WHERE organization_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAPIKeysByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedByUserID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.Scopes,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET revoked_at = now()
WHERE id = $1
  AND revoked_at IS NULL
RETURNING id, organization_id, created_by_user_id, name, key_prefix, key_hash, scopes, last_used_at, revoked_at, created_at
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedByUserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :one
UPDATE api_keys
SET last_used_at = now()
WHERE id = $1
RETURNING id, organization_id, created_by_user_id, name, key_prefix, key_hash, scopes, last_used_at, revoked_at, created_at
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, touchAPIKeyLastUsed, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedByUserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}
