// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: audit_logs.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    organization_id,
    actor_type,
    actor_user_id,
    actor_api_key_id,
    action,
    target_type,
    target_id,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, organization_id, actor_type, actor_user_id, actor_api_key_id, action, target_type, target_id, metadata, occurred_at
`

type CreateAuditLogParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	ActorType      string      `json:"actor_type"`
	ActorUserID    pgtype.UUID `json:"actor_user_id"`
	ActorApiKeyID  pgtype.UUID `json:"actor_api_key_id"`
	Action         string      `json:"action"`
	TargetType     string      `json:"target_type"`
	TargetID       string      `json:"target_id"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.OrganizationID,
		arg.ActorType,
		arg.ActorUserID,
		arg.ActorApiKeyID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ActorType,
		&i.ActorUserID,
		&i.ActorApiKeyID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Metadata,
		&i.OccurredAt,
	)
	return i, err
}

const listAuditLogsByOrganization = `-- name: ListAuditLogsByOrganization :many
SELECT id, organization_id, actor_type, actor_user_id, actor_api_key_id, action, target_type, target_id, metadata, occurred_at
FROM audit_logs
WHERE organization_id = $1
ORDER BY occurred_at DESC, id DESC
LIMIT $2
OFFSET $3
`

type ListAuditLogsByOrganizationParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListAuditLogsByOrganization(ctx context.Context, arg ListAuditLogsByOrganizationParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ActorType,
			&i.ActorUserID,
			&i.ActorApiKeyID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
