// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth_refresh_tokens.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthRefreshToken = `-- name: CreateAuthRefreshToken :one
INSERT INTO auth_refresh_tokens (
    user_id,
    token_hash,
    expires_at
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, user_id, token_hash, expires_at, created_at, used_at, revoked_at, replaced_by_token_id
`

type CreateAuthRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthRefreshToken(ctx context.Context, arg CreateAuthRefreshTokenParams) (AuthRefreshToken, error) {
	row := q.db.QueryRow(ctx, createAuthRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i AuthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.ReplacedByTokenID,
	)
	return i, err
}

const getAuthRefreshTokenByTokenHash = `-- name: GetAuthRefreshTokenByTokenHash :one
SELECT id, user_id, token_hash, expires_at, created_at, used_at, revoked_at, replaced_by_token_id
FROM auth_refresh_tokens
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetAuthRefreshTokenByTokenHash(ctx context.Context, tokenHash string) (AuthRefreshToken, error) {
	row := q.db.QueryRow(ctx, getAuthRefreshTokenByTokenHash, tokenHash)
	var i AuthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.ReplacedByTokenID,
	)
	return i, err
}

const revokeAuthRefreshToken = `-- name: RevokeAuthRefreshToken :one
UPDATE auth_refresh_tokens
SET revoked_at = now()
WHERE id = $1
  AND revoked_at IS NULL
RETURNING id, user_id, token_hash, expires_at, created_at, used_at, revoked_at, replaced_by_token_id
`

func (q *Queries) RevokeAuthRefreshToken(ctx context.Context, id pgtype.UUID) (AuthRefreshToken, error) {
	row := q.db.QueryRow(ctx, revokeAuthRefreshToken, id)
	var i AuthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.ReplacedByTokenID,
	)
	return i, err
}

const rotateAuthRefreshToken = `-- name: RotateAuthRefreshToken :one
UPDATE auth_refresh_tokens
SET used_at = now(),
    replaced_by_token_id = $2
WHERE id = $1
  AND used_at IS NULL
  AND revoked_at IS NULL
RETURNING id, user_id, token_hash, expires_at, created_at, used_at, revoked_at, replaced_by_token_id
`

type RotateAuthRefreshTokenParams struct {
	ID                pgtype.UUID `json:"id"`
	ReplacedByTokenID pgtype.UUID `json:"replaced_by_token_id"`
}

func (q *Queries) RotateAuthRefreshToken(ctx context.Context, arg RotateAuthRefreshTokenParams) (AuthRefreshToken, error) {
	row := q.db.QueryRow(ctx, rotateAuthRefreshToken, arg.ID, arg.ReplacedByTokenID)
	var i AuthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.ReplacedByTokenID,
	)
	return i, err
}
