// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth_webauthn_credentials.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthWebAuthnCredential = `-- name: CreateAuthWebAuthnCredential :one
INSERT INTO auth_webauthn_credentials (
    user_id,
    credential_id,
    credential_ciphertext,
    credential_nonce
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, user_id, credential_id, credential_ciphertext, credential_nonce, created_at, last_used_at
`

type CreateAuthWebAuthnCredentialParams struct {
	UserID               pgtype.UUID `json:"user_id"`
	CredentialID         []byte      `json:"credential_id"`
	CredentialCiphertext []byte      `json:"credential_ciphertext"`
	CredentialNonce      []byte      `json:"credential_nonce"`
}

func (q *Queries) CreateAuthWebAuthnCredential(ctx context.Context, arg CreateAuthWebAuthnCredentialParams) (AuthWebauthnCredential, error) {
	row := q.db.QueryRow(ctx, createAuthWebAuthnCredential,
		arg.UserID,
		arg.CredentialID,
		arg.CredentialCiphertext,
		arg.CredentialNonce,
	)
	var i AuthWebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.CredentialCiphertext,
		&i.CredentialNonce,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listAuthWebAuthnCredentialsByUserID = `-- name: ListAuthWebAuthnCredentialsByUserID :many
SELECT id, user_id, credential_id, credential_ciphertext, credential_nonce, created_at, last_used_at
FROM auth_webauthn_credentials
WHERE user_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListAuthWebAuthnCredentialsByUserID(ctx context.Context, userID pgtype.UUID) ([]AuthWebauthnCredential, error) {
	rows, err := q.db.Query(ctx, listAuthWebAuthnCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthWebauthnCredential{}
	for rows.Next() {
		var i AuthWebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.CredentialCiphertext,
			&i.CredentialNonce,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthWebAuthnCredential = `-- name: UpdateAuthWebAuthnCredential :one
UPDATE auth_webauthn_credentials
SET credential_ciphertext = $2,
    credential_nonce = $3,
    last_used_at = now()
WHERE id = $1
RETURNING id, user_id, credential_id, credential_ciphertext, credential_nonce, created_at, last_used_at
`

type UpdateAuthWebAuthnCredentialParams struct {
	ID                   pgtype.UUID `json:"id"`
	CredentialCiphertext []byte      `json:"credential_ciphertext"`
	CredentialNonce      []byte      `json:"credential_nonce"`
}

func (q *Queries) UpdateAuthWebAuthnCredential(ctx context.Context, arg UpdateAuthWebAuthnCredentialParams) (AuthWebauthnCredential, error) {
	row := q.db.QueryRow(ctx, updateAuthWebAuthnCredential, arg.ID, arg.CredentialCiphertext, arg.CredentialNonce)
	var i AuthWebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.CredentialCiphertext,
		&i.CredentialNonce,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}
