// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth_webauthn_sessions.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthWebAuthnSession = `-- name: CreateAuthWebAuthnSession :one
INSERT INTO auth_webauthn_sessions (
    user_id,
    flow,
    session_data,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, user_id, flow, session_data, expires_at, created_at
`

type CreateAuthWebAuthnSessionParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Flow        string             `json:"flow"`
	SessionData []byte             `json:"session_data"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthWebAuthnSession(ctx context.Context, arg CreateAuthWebAuthnSessionParams) (AuthWebauthnSession, error) {
	row := q.db.QueryRow(ctx, createAuthWebAuthnSession,
		arg.UserID,
		arg.Flow,
		arg.SessionData,
		arg.ExpiresAt,
	)
	var i AuthWebauthnSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Flow,
		&i.SessionData,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthWebAuthnSession = `-- name: DeleteAuthWebAuthnSession :exec
DELETE FROM auth_webauthn_sessions
WHERE id = $1
`

func (q *Queries) DeleteAuthWebAuthnSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthWebAuthnSession, id)
	return err
}

const getAuthWebAuthnSessionByID = `-- name: GetAuthWebAuthnSessionByID :one
SELECT id, user_id, flow, session_data, expires_at, created_at
FROM auth_webauthn_sessions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAuthWebAuthnSessionByID(ctx context.Context, id pgtype.UUID) (AuthWebauthnSession, error) {
	row := q.db.QueryRow(ctx, getAuthWebAuthnSessionByID, id)
	var i AuthWebauthnSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Flow,
		&i.SessionData,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
