// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: memberships.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (
    organization_id,
    user_id,
    role
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, organization_id, user_id, role, created_at
`

type CreateMembershipParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Role           string      `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.OrganizationID, arg.UserID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, organization_id, user_id, role, created_at
FROM memberships
WHERE organization_id = $1
  AND user_id = $2
LIMIT 1
`

type GetMembershipParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.OrganizationID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listMembershipsByOrganization = `-- name: ListMembershipsByOrganization :many
SELECT id, organization_id, user_id, role, created_at
FROM memberships
WHERE organization_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListMembershipsByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT id, organization_id, user_id, role, created_at
FROM memberships
WHERE user_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListMembershipsByUser(ctx context.Context, userID pgtype.UUID) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Membership{}
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
