// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	Name            string             `json:"name"`
	KeyPrefix       string             `json:"key_prefix"`
	KeyHash         string             `json:"key_hash"`
	Scopes          []string           `json:"scopes"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	ActorType      string             `json:"actor_type"`
	ActorUserID    pgtype.UUID        `json:"actor_user_id"`
	ActorApiKeyID  pgtype.UUID        `json:"actor_api_key_id"`
	Action         string             `json:"action"`
	TargetType     string             `json:"target_type"`
	TargetID       string             `json:"target_id"`
	Metadata       []byte             `json:"metadata"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
}

type AuthRefreshToken struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	TokenHash         string             `json:"token_hash"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UsedAt            pgtype.Timestamptz `json:"used_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	ReplacedByTokenID pgtype.UUID        `json:"replaced_by_token_id"`
}

type AuthWebauthnCredential struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               pgtype.UUID        `json:"user_id"`
	CredentialID         []byte             `json:"credential_id"`
	CredentialCiphertext []byte             `json:"credential_ciphertext"`
	CredentialNonce      []byte             `json:"credential_nonce"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	LastUsedAt           pgtype.Timestamptz `json:"last_used_at"`
}

type AuthWebauthnSession struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Flow        string             `json:"flow"`
	SessionData []byte             `json:"session_data"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Membership struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                 pgtype.UUID        `json:"id"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	DisplayName        string             `json:"display_name"`
	IsSystemAdmin      bool               `json:"is_system_admin"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	WebauthnUserHandle []byte             `json:"webauthn_user_handle"`
}

type UserTotpCredential struct {
	UserID           pgtype.UUID        `json:"user_id"`
	SecretCiphertext []byte             `json:"secret_ciphertext"`
	SecretNonce      []byte             `json:"secret_nonce"`
	EnabledAt        pgtype.Timestamptz `json:"enabled_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
