// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: organizations.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    slug,
    name
) VALUES (
    $1,
    $2
)
RETURNING id, slug, name, created_at, updated_at
`

type CreateOrganizationParams struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Slug, arg.Name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, slug, name, created_at, updated_at
FROM organizations
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, slug, name, created_at, updated_at
FROM organizations
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizationsByUser = `-- name: ListOrganizationsByUser :many
SELECT
    o.id,
    o.slug,
    o.name,
    o.created_at,
    o.updated_at,
    m.role
FROM organizations AS o
JOIN memberships AS m
    ON m.organization_id = o.id
WHERE m.user_id = $1
ORDER BY o.created_at ASC, o.id ASC
`

type ListOrganizationsByUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Role      string             `json:"role"`
}

func (q *Queries) ListOrganizationsByUser(ctx context.Context, userID pgtype.UUID) ([]ListOrganizationsByUserRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsByUserRow{}
	for rows.Next() {
		var i ListOrganizationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
