// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAuthRefreshToken(ctx context.Context, arg CreateAuthRefreshTokenParams) (AuthRefreshToken, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAuthRefreshTokenByTokenHash(ctx context.Context, tokenHash string) (AuthRefreshToken, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListMembershipsByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]Membership, error)
	ListMembershipsByUser(ctx context.Context, userID pgtype.UUID) ([]Membership, error)
	ListOrganizationsByUser(ctx context.Context, userID pgtype.UUID) ([]ListOrganizationsByUserRow, error)
	ListUsersByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]ListUsersByOrganizationRow, error)
	RevokeAuthRefreshToken(ctx context.Context, id pgtype.UUID) (AuthRefreshToken, error)
	RotateAuthRefreshToken(ctx context.Context, arg RotateAuthRefreshTokenParams) (AuthRefreshToken, error)
}

var _ Querier = (*Queries)(nil)
