// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateAuthRefreshToken(ctx context.Context, arg CreateAuthRefreshTokenParams) (AuthRefreshToken, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUserTOTPCredential(ctx context.Context, userID pgtype.UUID) error
	EnableUserTOTPCredential(ctx context.Context, userID pgtype.UUID) (UserTotpCredential, error)
	GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error)
	GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error)
	GetAuthRefreshTokenByTokenHash(ctx context.Context, tokenHash string) (AuthRefreshToken, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserTOTPCredentialByUserID(ctx context.Context, userID pgtype.UUID) (UserTotpCredential, error)
	ListAPIKeysByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]ApiKey, error)
	ListAuditLogsByOrganization(ctx context.Context, arg ListAuditLogsByOrganizationParams) ([]AuditLog, error)
	ListMembershipsByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]Membership, error)
	ListMembershipsByUser(ctx context.Context, userID pgtype.UUID) ([]Membership, error)
	ListOrganizationsByUser(ctx context.Context, userID pgtype.UUID) ([]ListOrganizationsByUserRow, error)
	ListUsersByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]ListUsersByOrganizationRow, error)
	RevokeAPIKey(ctx context.Context, id pgtype.UUID) (ApiKey, error)
	RevokeAuthRefreshToken(ctx context.Context, id pgtype.UUID) (AuthRefreshToken, error)
	RotateAuthRefreshToken(ctx context.Context, arg RotateAuthRefreshTokenParams) (AuthRefreshToken, error)
	TouchAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) (ApiKey, error)
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (Membership, error)
	UpsertUserTOTPCredential(ctx context.Context, arg UpsertUserTOTPCredentialParams) (UserTotpCredential, error)
}

var _ Querier = (*Queries)(nil)
