// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user_totp_credentials.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserTOTPCredential = `-- name: DeleteUserTOTPCredential :exec
DELETE FROM user_totp_credentials
WHERE user_id = $1
`

func (q *Queries) DeleteUserTOTPCredential(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserTOTPCredential, userID)
	return err
}

const enableUserTOTPCredential = `-- name: EnableUserTOTPCredential :one
UPDATE user_totp_credentials
SET enabled_at = now(),
    updated_at = now()
WHERE user_id = $1
RETURNING user_id, secret_ciphertext, secret_nonce, enabled_at, created_at, updated_at
`

func (q *Queries) EnableUserTOTPCredential(ctx context.Context, userID pgtype.UUID) (UserTotpCredential, error) {
	row := q.db.QueryRow(ctx, enableUserTOTPCredential, userID)
	var i UserTotpCredential
	err := row.Scan(
		&i.UserID,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.EnabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTOTPCredentialByUserID = `-- name: GetUserTOTPCredentialByUserID :one
SELECT user_id, secret_ciphertext, secret_nonce, enabled_at, created_at, updated_at
FROM user_totp_credentials
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetUserTOTPCredentialByUserID(ctx context.Context, userID pgtype.UUID) (UserTotpCredential, error) {
	row := q.db.QueryRow(ctx, getUserTOTPCredentialByUserID, userID)
	var i UserTotpCredential
	err := row.Scan(
		&i.UserID,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.EnabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserTOTPCredential = `-- name: UpsertUserTOTPCredential :one
INSERT INTO user_totp_credentials (
    user_id,
    secret_ciphertext,
    secret_nonce,
    enabled_at,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    NULL,
    now(),
    now()
)
ON CONFLICT (user_id) DO UPDATE
SET secret_ciphertext = EXCLUDED.secret_ciphertext,
    secret_nonce = EXCLUDED.secret_nonce,
    enabled_at = NULL,
    updated_at = now()
RETURNING user_id, secret_ciphertext, secret_nonce, enabled_at, created_at, updated_at
`

type UpsertUserTOTPCredentialParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	SecretCiphertext []byte      `json:"secret_ciphertext"`
	SecretNonce      []byte      `json:"secret_nonce"`
}

func (q *Queries) UpsertUserTOTPCredential(ctx context.Context, arg UpsertUserTOTPCredentialParams) (UserTotpCredential, error) {
	row := q.db.QueryRow(ctx, upsertUserTOTPCredential, arg.UserID, arg.SecretCiphertext, arg.SecretNonce)
	var i UserTotpCredential
	err := row.Scan(
		&i.UserID,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.EnabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
