// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password_hash,
    display_name,
    is_system_admin
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, email, password_hash, display_name, is_system_admin, created_at, updated_at
`

type CreateUserParams struct {
	Email         string `json:"email"`
	PasswordHash  string `json:"password_hash"`
	DisplayName   string `json:"display_name"`
	IsSystemAdmin bool   `json:"is_system_admin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.IsSystemAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, is_system_admin, created_at, updated_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, is_system_admin, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByOrganization = `-- name: ListUsersByOrganization :many
SELECT
    u.id,
    u.email,
    u.password_hash,
    u.display_name,
    u.is_system_admin,
    u.created_at,
    u.updated_at,
    m.role
FROM users AS u
JOIN memberships AS m
    ON m.user_id = u.id
WHERE m.organization_id = $1
ORDER BY u.created_at ASC, u.id ASC
`

type ListUsersByOrganizationRow struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	DisplayName   string             `json:"display_name"`
	IsSystemAdmin bool               `json:"is_system_admin"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Role          string             `json:"role"`
}

func (q *Queries) ListUsersByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]ListUsersByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listUsersByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByOrganizationRow{}
	for rows.Next() {
		var i ListUsersByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.DisplayName,
			&i.IsSystemAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
